g flop-agent -
g flop-signer-acquisition -
u flop-signer - "FLOP Policy Signer" /var/lib/flop-policy-signer /usr/sbin/nologin
u flop-signer-reader - "FLOP Policy Signer Reader" /var/lib/flop-policy-signer-input /usr/sbin/nologin
m flop-signer flop-signer-acquisition
m flop-signer-reader flop-signer-acquisition
